<?php
$title = $this->translate('Sign in');
$this->headTitle($title);
?>

<div class="signin-img text-center">
    <a class="signin-logo" href="<?php echo $this->url('home'); ?>">
        <img src="<?php echo $this->basePath('img/logo128.png') ?>" alt="<?php echo $this->translate('Home'); ?>"/>
    </a>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title text-center"><?php echo $title ?></h3>
    </div>
    <div class="panel-body">
        <?php echo $this->tssFlashMessenger()->render(); ?>
        <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            <?php echo $this->tssFormRow($form->get('username')); ?>
            <?php echo $this->tssFormRow($form->get('password')); ?>

            <div class="row">
                <div class="col-xs-6">
                    <?php echo $this->tssFormCheckbox($form->get('remember-me')); ?>
                </div>
                <div class="col-xs-6">
                    <div class="checkbox">
                        <a href="<?php //echo $this->url('home/recuperar-senha'); ?>"><?php echo $this->translate('Forgotten password'); ?></a>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-6">
                    <!-- Change this to a button or input when using this as a form -->
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
                <div class="col-xs-6">
                    <div><?php echo $this->translate('Don\'t have an account?'); ?></div>

                    <strong><a href="<?php echo $this->url($authRoutes['signup']['name']);?>"><?php echo $this->translate('Sign up'); ?></a></strong>
                </div>
            </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>