<footer>
    <div class="container-fluid text-center">
        <i class="fa fa-circle"></i>
        <i class="fa fa-circle-thin"></i>
        <i class="fa fa-copyright"></i><span class="sr-only">&copy</span> 2015 - <?php echo date('Y') ?> by TSS. <?php echo $this->translate('All rights reserved.') ?>
        <i class="fa fa-circle"></i>
        <i class="fa fa-circle-thin"></i>
    </div>
</footer>